apiVersion: v1
kind: Pod
metadata: 
 name: postgres-pod
 labels:
   name: postgres-pod
   app: demo-voting-app
   
spec:
 constainers: 
  - name: postgres
    image: postgress:9.4
    ports: 
    - containerPort: 5432
    