apiVersion: v1
kind: Pod
metadata: 
 name: worker-app-pod
 labels:
   name: worker-app-pod
   app: demo-voting-app
   
spec:
 constainers: 
  - name: worker-app
    image: dockersamples/examplevotingapp_worker
    ports: 
    - containerPort: 80
    